### ISSUE TITLE
Writing document for eMMC host controller

### ISSUE THREAD

**Issue by AzamatBeksadaev** [subutai-io/pars#27]
Preparing document covers controller block structure, signals, functionality and other specific things.

**Comment by AzamatBeksadaev** [comment]
Figure is uploaded to use it in Wiki 
![screenshot from 2016-08-03 19 37 48](https://cloud.githubusercontent.com/assets/10692937/17367926/d20e1862-59b3-11e6-9ad5-a097cf89128a.png)

**Comment by AzamatBeksadaev** [comment]
Figure is uploaded to use it in Wiki 
![screenshot from 2016-08-11 12 21 58](https://cloud.githubusercontent.com/assets/10692937/17580182/71e789e4-5fbe-11e6-8281-c51b7037fbcf.png)

**Comment by AzamatBeksadaev** [comment]
Figure is uploaded to use it in Wiki
![screenshot from 2016-08-11 17 33 05](https://cloud.githubusercontent.com/assets/10692937/17587613/393371ee-5feb-11e6-988a-ba9a8b4363ff.png)

**Comment by akarasulu** [comment]
Why are you not authoring this on wiki pages?

**Comment by akarasulu** [comment]
Please disregard previous comment. I see the wiki pages now.... this documentation is great !!!

**Comment by AzamatBeksadaev** [comment]
Wiki applies only link to image. There are no ways to upload images directly. So, here I store images in cloud.githubusercontent.com and link them in Wiki.

**Comment by AzamatBeksadaev** [comment]
Wiki image
![screenshot from 2016-08-12 10 39 46](https://cloud.githubusercontent.com/assets/10692937/17613246/e846c758-607c-11e6-8681-b0142bb6a7a6.png)

**Comment by AzamatBeksadaev** [comment]
![screenshot from 2016-08-12 11 11 47](https://cloud.githubusercontent.com/assets/10692937/17613340/dbb0f120-607d-11e6-9dba-dc2d82a8e432.png)

**Comment by AzamatBeksadaev** [comment]
![screenshot from 2016-08-12 11 51 39](https://cloud.githubusercontent.com/assets/10692937/17613874/671b7000-6083-11e6-829a-988e57a7fdac.png)

**Comment by AzamatBeksadaev** [comment]
![screenshot from 2016-08-12 12 06 18](https://cloud.githubusercontent.com/assets/10692937/17614118/7435eec6-6085-11e6-8984-552a23d28351.png)

**Comment by AzamatBeksadaev** [comment]
Base information about controller is written to the wiki.
